// This file is a part of ARDEN.
//
// Look, but don't touch.
//
// Copyright 2017 [bk]door.maus

#include "ganymede/ganymede.hpp"
#include "celia/common/utility.hpp"

std::size_t celia::utility::get_texture_pixel_data_size(
	int format, int type,
	int width, int height, int depth)
{
	std::size_t num_pixels = width * height * depth;

	std::size_t num_components;
	switch (format)
	{
		case GL_RED:
		case GL_DEPTH_COMPONENT:
		case GL_STENCIL_INDEX:
			num_components = 1;
			break;
		case GL_RG:
			num_components = 2;
			break;
		case GL_RGB:
		case GL_BGR:
			num_components = 3;
			break;
		case GL_RGBA:
		case GL_BGRA:
			num_components = 4;
			break;
	}

	switch (type)
	{
		case GL_UNSIGNED_BYTE:
		case GL_BYTE:
			return num_components * num_pixels;
		case GL_UNSIGNED_BYTE_3_3_2:
		case GL_UNSIGNED_BYTE_2_3_3_REV:
			return num_pixels;
		case GL_UNSIGNED_SHORT:
		case GL_SHORT:
			return num_components * num_pixels * 2;
		case GL_UNSIGNED_SHORT_5_6_5:
		case GL_UNSIGNED_SHORT_5_6_5_REV:
		case GL_UNSIGNED_SHORT_4_4_4_4:
		case GL_UNSIGNED_SHORT_4_4_4_4_REV:
		case GL_UNSIGNED_SHORT_5_5_5_1:
		case GL_UNSIGNED_SHORT_1_5_5_5_REV:
			return num_pixels * 2;
		case GL_UNSIGNED_INT:
		case GL_INT:
			return num_pixels * num_components * 4;
		case GL_UNSIGNED_INT_8_8_8_8:
		case GL_UNSIGNED_INT_8_8_8_8_REV:
		case GL_UNSIGNED_INT_10_10_10_2:
		case GL_UNSIGNED_INT_2_10_10_10_REV:
		case GL_UNSIGNED_INT_10F_11F_11F_REV:
			return num_pixels * 4;
		case GL_FLOAT:
			return num_pixels * num_components * 4;
		case GL_R11F_G11F_B10F_EXT:
			return num_pixels * 4;
	}

	return 0;
}

std::size_t celia::utility::get_pname_count(int pname)
{
	switch (pname)
	{
		case GL_ACTIVE_TEXTURE:
			return 1;
		case GL_ALIASED_LINE_WIDTH_RANGE:
			return 2;
		case GL_ARRAY_BUFFER_BINDING:
			return 1;
		case GL_BLEND:
			return 1;
		case GL_BLEND_DST_ALPHA:
			return 1;
		case GL_BLEND_DST_RGB:
			return 1;
		case GL_BLEND_EQUATION_RGB:
			return 1;
		case GL_BLEND_EQUATION_ALPHA:
			return 1;
		case GL_BLEND_SRC_ALPHA:
			return 1;
		case GL_BLEND_SRC_RGB:
			return 1;
		case GL_COLOR_CLEAR_VALUE:
			return 4;
		case GL_COLOR_LOGIC_OP:
			return 1;
		case GL_COLOR_WRITEMASK:
			return 4;
		case GL_COMPRESSED_TEXTURE_FORMATS:
			return 0;
		case GL_DISPATCH_INDIRECT_BUFFER_BINDING:
			return 1;
		case GL_MAX_DEBUG_GROUP_STACK_DEPTH:
			return 1;
		case GL_DEBUG_GROUP_STACK_DEPTH:
			return 1;
		case GL_CONTEXT_FLAGS:
			return 1;
		case GL_CULL_FACE:
			return 1;
		case GL_CURRENT_PROGRAM:
			return 1;
		case GL_DEPTH_CLEAR_VALUE:
			return 1;
		case GL_DEPTH_FUNC:
			return 1;
		case GL_DEPTH_RANGE:
			return 2;
		case GL_DEPTH_TEST:
			return 1;
		case GL_DEPTH_WRITEMASK:
			return 1;
		case GL_DITHER:
			return 1;
		case GL_DOUBLEBUFFER:
			return 1;
		case GL_DRAW_BUFFER:
		case GL_DRAW_BUFFER0:
		case GL_DRAW_BUFFER1:
		case GL_DRAW_BUFFER2:
		case GL_DRAW_BUFFER3:
		case GL_DRAW_BUFFER4:
		case GL_DRAW_BUFFER5:
		case GL_DRAW_BUFFER6:
		case GL_DRAW_BUFFER7:
		case GL_DRAW_BUFFER8:
		case GL_DRAW_BUFFER9:
		case GL_DRAW_BUFFER10:
		case GL_DRAW_BUFFER11:
		case GL_DRAW_BUFFER12:
		case GL_DRAW_BUFFER13:
		case GL_DRAW_BUFFER14:
		case GL_DRAW_BUFFER15:
			return 1;
		case GL_DRAW_FRAMEBUFFER_BINDING:
			return 1;
		case GL_READ_FRAMEBUFFER_BINDING:
			return 1;
		case GL_ELEMENT_ARRAY_BUFFER_BINDING:
			return 1;
		case GL_FRAGMENT_SHADER_DERIVATIVE_HINT:
			return 1;
		case GL_IMPLEMENTATION_COLOR_READ_FORMAT:
			return 1;
		case GL_IMPLEMENTATION_COLOR_READ_TYPE:
			return 1;
		case GL_LINE_SMOOTH:
			return 1;
		case GL_LINE_SMOOTH_HINT:
			return 1;
		case GL_LINE_WIDTH:
			return 1;
		case GL_LAYER_PROVOKING_VERTEX:
			return 1;
		case GL_LOGIC_OP_MODE:
			return 1;
		case GL_MAJOR_VERSION:
			return 1;
		case GL_MAX_3D_TEXTURE_SIZE:
			return 1;
		case GL_MAX_ARRAY_TEXTURE_LAYERS:
			return 1;
		case GL_MAX_CLIP_DISTANCES:
			return 1;
		case GL_MAX_COLOR_TEXTURE_SAMPLES:
			return 1;
		case GL_MAX_COMBINED_ATOMIC_COUNTERS:
			return 1;
		case GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS:
			return 1;
		case GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS:
			return 1;
		case GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS:
			return 1;
		case GL_MAX_COMBINED_UNIFORM_BLOCKS:
			return 1;
		case GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS:
			return 1;
		case GL_MAX_CUBE_MAP_TEXTURE_SIZE:
			return 1;
		case GL_MAX_DEPTH_TEXTURE_SAMPLES:
			return 1;
		case GL_MAX_DRAW_BUFFERS:
			return 1;
		case GL_MAX_DUAL_SOURCE_DRAW_BUFFERS:
			return 1;
		case GL_MAX_ELEMENTS_INDICES:
			return 1;
		case GL_MAX_ELEMENTS_VERTICES:
			return 1;
		case GL_MAX_FRAGMENT_ATOMIC_COUNTERS:
			return 1;
		case GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS:
			return 1;
		case GL_MAX_FRAGMENT_INPUT_COMPONENTS:
			return 1;
		case GL_MAX_FRAGMENT_UNIFORM_COMPONENTS:
			return 1;
		case GL_MAX_FRAGMENT_UNIFORM_VECTORS:
			return 1;
		case GL_MAX_FRAGMENT_UNIFORM_BLOCKS:
			return 1;
		case GL_MAX_FRAMEBUFFER_WIDTH:
			return 1;
		case GL_MAX_FRAMEBUFFER_HEIGHT:
			return 1;
		case GL_MAX_FRAMEBUFFER_LAYERS:
			return 1;
		case GL_MAX_FRAMEBUFFER_SAMPLES:
			return 1;
		case GL_MAX_GEOMETRY_ATOMIC_COUNTERS:
			return 1;
		case GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS:
			return 1;
		case GL_MAX_GEOMETRY_INPUT_COMPONENTS:
			return 1;
		case GL_MAX_GEOMETRY_OUTPUT_COMPONENTS:
			return 1;
		case GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS:
			return 1;
		case GL_MAX_GEOMETRY_UNIFORM_BLOCKS:
			return 1;
		case GL_MAX_GEOMETRY_UNIFORM_COMPONENTS:
			return 1;
		case GL_MAX_INTEGER_SAMPLES:
			return 1;
		case GL_MIN_MAP_BUFFER_ALIGNMENT:
			return 1;
		case GL_MAX_LABEL_LENGTH:
			return 1;
		case GL_MAX_PROGRAM_TEXEL_OFFSET:
			return 1;
		case GL_MIN_PROGRAM_TEXEL_OFFSET:
			return 1;
		case GL_MAX_RECTANGLE_TEXTURE_SIZE:
			return 1;
		case GL_MAX_RENDERBUFFER_SIZE:
			return 1;
		case GL_MAX_SAMPLE_MASK_WORDS:
			return 1;
		case GL_MAX_SERVER_WAIT_TIMEOUT:
			return 1;
		case GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS:
			return 1;
		case GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS:
			return 1;
		case GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS:
			return 1;
		case GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS:
			return 1;
		case GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS:
			return 1;
		case GL_MAX_TEXTURE_BUFFER_SIZE:
			return 1;
		case GL_MAX_TEXTURE_IMAGE_UNITS:
			return 1;
		case GL_MAX_TEXTURE_LOD_BIAS:
			return 1;
		case GL_MAX_TEXTURE_SIZE:
			return 1;
		case GL_MAX_UNIFORM_BUFFER_BINDINGS:
			return 1;
		case GL_MAX_UNIFORM_BLOCK_SIZE:
			return 1;
		case GL_MAX_UNIFORM_LOCATIONS:
			return 1;
		case GL_MAX_VARYING_COMPONENTS:
			return 1;
		case GL_MAX_VARYING_VECTORS:
			return 1;
		case GL_MAX_VERTEX_ATOMIC_COUNTERS:
			return 1;
		case GL_MAX_VERTEX_ATTRIBS:
			return 1;
		case GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS:
			return 1;
		case GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS:
			return 1;
		case GL_MAX_VERTEX_UNIFORM_COMPONENTS:
			return 1;
		case GL_MAX_VERTEX_UNIFORM_VECTORS:
			return 1;
		case GL_MAX_VERTEX_OUTPUT_COMPONENTS:
			return 1;
		case GL_MAX_VERTEX_UNIFORM_BLOCKS:
			return 1;
		case GL_MAX_VIEWPORT_DIMS:
			return 1;
		case GL_MAX_VIEWPORTS:
			return 1;
		case GL_MINOR_VERSION:
			return 1;
		case GL_NUM_COMPRESSED_TEXTURE_FORMATS:
			return 1;
		case GL_NUM_EXTENSIONS:
			return 1;
		case GL_NUM_PROGRAM_BINARY_FORMATS:
			return 1;
		case GL_NUM_SHADER_BINARY_FORMATS:
			return 1;
		case GL_PACK_ALIGNMENT:
			return 1;
		case GL_PACK_IMAGE_HEIGHT:
			return 1;
		case GL_PACK_LSB_FIRST:
			return 1;
		case GL_PACK_ROW_LENGTH:
			return 1;
		case GL_PACK_SKIP_IMAGES:
			return 1;
		case GL_PACK_SKIP_PIXELS:
			return 1;
		case GL_PACK_SKIP_ROWS:
			return 1;
		case GL_PACK_SWAP_BYTES:
			return 1;
		case GL_PIXEL_PACK_BUFFER_BINDING:
			return 1;
		case GL_PIXEL_UNPACK_BUFFER_BINDING:
			return 1;
		case GL_POINT_FADE_THRESHOLD_SIZE:
			return 1;
		case GL_PRIMITIVE_RESTART_INDEX:
			return 1;
		case GL_PROGRAM_BINARY_FORMATS:
			return 0;
		case GL_PROGRAM_PIPELINE_BINDING:
			return 1;
		case GL_PROGRAM_POINT_SIZE:
			return 1;
		case GL_PROVOKING_VERTEX:
			return 1;
		case GL_POINT_SIZE:
			return 1;
		case GL_POINT_SIZE_GRANULARITY:
			return 1;
		case GL_POINT_SIZE_RANGE:
			return 2;
		case GL_POLYGON_OFFSET_FACTOR:
			return 1;
		case GL_POLYGON_OFFSET_UNITS:
			return 1;
		case GL_POLYGON_OFFSET_FILL:
			return 1;
		case GL_POLYGON_OFFSET_LINE:
			return 1;
		case GL_POLYGON_OFFSET_POINT:
			return 1;
		case GL_POLYGON_SMOOTH:
			return 1;
		case GL_POLYGON_SMOOTH_HINT:
			return 1;
		case GL_READ_BUFFER:
			return 1;
		case GL_RENDERBUFFER_BINDING:
			return 1;
		case GL_SAMPLE_BUFFERS:
			return 1;
		case GL_SAMPLE_COVERAGE_VALUE:
			return 1;
		case GL_SAMPLE_COVERAGE_INVERT:
			return 1;
		case GL_SAMPLER_BINDING:
			return 1;
		case GL_SAMPLES:
			return 1;
		case GL_SCISSOR_BOX:
			return 4;
		case GL_SCISSOR_TEST:
			return 1;
		case GL_SHADER_COMPILER:
			return 1;
		case GL_SHADER_STORAGE_BUFFER_BINDING:
			return 1;
		case GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT:
			return 1;
		case GL_SHADER_STORAGE_BUFFER_START:
			return 1;
		case GL_SHADER_STORAGE_BUFFER_SIZE:
			return 1;
		case GL_SMOOTH_LINE_WIDTH_RANGE:
			return 1;
		case GL_SMOOTH_LINE_WIDTH_GRANULARITY:
			return 1;
		case GL_STENCIL_BACK_FAIL:
			return 1;
		case GL_STENCIL_BACK_FUNC:
			return 1;
		case GL_STENCIL_BACK_PASS_DEPTH_FAIL:
			return 1;
		case GL_STENCIL_BACK_PASS_DEPTH_PASS:
			return 1;
		case GL_STENCIL_BACK_REF:
			return 1;
		case GL_STENCIL_BACK_VALUE_MASK:
			return 1;
		case GL_STENCIL_BACK_WRITEMASK:
			return 1;
		case GL_STENCIL_CLEAR_VALUE:
			return 1;
		case GL_STENCIL_FAIL:
			return 1;
		case GL_STENCIL_FUNC:
			return 1;
		case GL_STENCIL_PASS_DEPTH_FAIL:
			return 1;
		case GL_STENCIL_PASS_DEPTH_PASS:
			return 1;
		case GL_STENCIL_REF:
			return 1;
		case GL_STENCIL_TEST:
			return 1;
		case GL_STENCIL_VALUE_MASK:
			return 1;
		case GL_STENCIL_WRITEMASK:
			return 1;
		case GL_STEREO:
			return 1;
		case GL_SUBPIXEL_BITS:
			return 1;
		case GL_TEXTURE_BINDING_1D:
			return 1;
		case GL_TEXTURE_BINDING_1D_ARRAY:
			return 1;
		case GL_TEXTURE_BINDING_2D:
			return 1;
		case GL_TEXTURE_BINDING_2D_ARRAY:
			return 1;
		case GL_TEXTURE_BINDING_2D_MULTISAMPLE:
			return 1;
		case GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY:
			return 1;
		case GL_TEXTURE_BINDING_3D:
			return 1;
		case GL_TEXTURE_BINDING_CUBE_MAP:
			return 1;
		case GL_TEXTURE_BINDING_RECTANGLE:
			return 1;
		case GL_TEXTURE_COMPRESSION_HINT:
			return 1;
		case GL_TEXTURE_BINDING_BUFFER:
			return 1;
		case GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT:
			return 1;
		case GL_TIMESTAMP:
			return 1;
		case GL_TRANSFORM_FEEDBACK_BUFFER_BINDING:
			return 1;
		case GL_TRANSFORM_FEEDBACK_BUFFER_START:
			return 1;
		case GL_TRANSFORM_FEEDBACK_BUFFER_SIZE:
			return 1;
		case GL_UNIFORM_BUFFER_BINDING:
			return 1;
		case GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT:
			return 1;
		case GL_UNIFORM_BUFFER_SIZE:
			return 1;
		case GL_UNIFORM_BUFFER_START:
			return 1;
		case GL_UNPACK_ALIGNMENT:
			return 1;
		case GL_UNPACK_IMAGE_HEIGHT:
			return 1;
		case GL_UNPACK_LSB_FIRST:
			return 1;
		case GL_UNPACK_ROW_LENGTH:
			return 1;
		case GL_UNPACK_SKIP_IMAGES:
			return 1;
		case GL_UNPACK_SKIP_PIXELS:
			return 1;
		case GL_UNPACK_SKIP_ROWS:
			return 1;
		case GL_UNPACK_SWAP_BYTES:
			return 1;
		case GL_VERTEX_ARRAY_BINDING:
			return 1;
		case GL_VERTEX_BINDING_DIVISOR:
			return 1;
		case GL_VERTEX_BINDING_OFFSET:
			return 1;
		case GL_VERTEX_BINDING_STRIDE:
			return 1;
		case GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET:
			return 1;
		case GL_MAX_VERTEX_ATTRIB_BINDINGS:
			return 1;
		case GL_VIEWPORT:
			return 4;
		case GL_VIEWPORT_BOUNDS_RANGE:
			return 2;
		case GL_VIEWPORT_INDEX_PROVOKING_VERTEX:
			return 1;
		case GL_VIEWPORT_SUBPIXEL_BITS:
			return 1;
		case GL_MAX_ELEMENT_INDEX:
			return 1;
	}

	return 0;
}
